{
 "title": "Algemeen dashboard beheer test",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "group",
    "label": "Naam",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},group)"
    }
   },
   {
    "name": "subgroup",
    "label": "Type",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", group=~\"$group\"},subgroup)"
    }
   },
   {
    "name": "instance",
    "label": "url",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\"},instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(up{job=\"apiserver\"},cluster)"
    }
   },
   {
    "name": "instance1",
    "label": "instance1",
    "query": {
     "query": "label_values(up{job=\"apiserver\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\"},namespace)"
    }
   },
   {
    "name": "cluster1",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\"},namespace)"
    }
   },
   {
    "name": "volume",
    "query": {
     "query": "label_values(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster1\", job=\"kubelet\", metrics_path=\"/metrics\", namespace=\"$namespace\"},persistentvolumeclaim)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Beschikbaarheid", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability (30d) > 99.000%",
   "type": "stat",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Read Availability (30d)",
   "type": "stat",
   "description": "How many percent of read requests (LIST,GET) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"read\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Write Availability (30d)",
   "type": "stat",
   "description": "How many percent of write requests (POST|PUT|PATCH|DELETE) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"write\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Globale status SSL certificaten",
   "type": "table-old",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "probe_success{job=\"$job\", group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'} - 0 "
    },
    {
     "expr": "probe_http_ssl{job=\"$job\", group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'} - 0"
    },
    {
     "expr": "probe_http_status_code{job=\"$job\",group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'} - 0"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{job=\"$job\",group=~'$group', subgroup=~\"$subgroup\", instance=~'$instance'}-time()"
    }
   ]
  },
  { "title": "Service status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Services",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "probe_success{group=~\"$group|flink_taskmanager|ignite|gateway|mysql|nacos|nginx|streamtau|uumsx\",subgroup=~\"$subgroup\",job=~\"$job$\"}",
     "legendFormat": "{{ group }}-{{ instance }}"
    }
   ]
  },
  { "title": "SSL certificaten", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\"}[$__interval]) * 100"
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Certificate validity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry{instance=~\"$instance\"} - time()) / (60*60*24)"
    }
   ]
  },
  {
   "title": "SSL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP status code",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "HTTP version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_http_version{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "SSL status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\",group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\",instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  { "title": "Antwoordtijd", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Totale antwoordtijd",
   "type": "graph",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Antwoordtijd per fase",
   "type": "graph",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", group=~\"$group\", subgroup=~\"$subgroup\",instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}